In [1]:
import keras
from keras.models import Sequential
from keras.layers import Dense,Dropout,Activation
from keras.optimizers import SGD
import numpy as np
import pandas as pd

2022-09-16 22:57:02.771337: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-09-16 22:57:02.771371: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
def pdf(x,tar):
    mean = np.mean(x)
    std = np.std(x)+tar
    y_out = 1/(std * np.sqrt(2 * np.pi)) * np.exp( - (x - mean)**2 / (2 * std**2))
    return y_out

In [3]:
a=2
b=10

#200 x's
m2 = 0.04

x = np.arange(a, b, m2)

print("L--------")
#Low concentration
low = 0.10
inc = 0

k=0
for i in range(20):
    #print(i)
    y = pdf(x,low+inc)
    y = np.insert(y, 0, 0, axis=0)
    
    if(i==0):
        data = {"amplitude 0":y}
        df = pd.DataFrame(data)
    else:    
        name = "amplitude "+str(k)
        df[name] = y
    
    
    inc = inc+0.005
    k+=1
    
print("M--------")
#Medium concentration
medium = 0.40
inc = 0
for i in range(20):
    #print(medium+inc)
    y = pdf(x,medium+inc)
    y = np.insert(y, 0, 1, axis=0)
    
    name = "amplitude "+str(k)
    df[name] = y
    
    inc = inc+0.005
    

    k+=1
    
    
print("H--------")
#High concentration
high = 0.60
inc = 0.0 
for i in range(20):
    #print(high+inc)
    y = pdf(x, high+inc)
    y = np.insert(y, 0, 2, axis=0)
    
    name = "amplitude "+str(k)
    df[name] = y
    
    inc = inc+0.005
    k+=1
    
#print(y)
df 

L--------
M--------
H--------


amplitude 0  amplitude 1  amplitude 2  amplitude 3  amplitude 4  \
0       0.000000     0.000000     0.000000     0.000000     0.000000   
1       0.042313     0.042464     0.042615     0.042765     0.042914   
2       0.043483     0.043634     0.043784     0.043933     0.044081   
3       0.044674     0.044824     0.044973     0.045121     0.045268   
4       0.045884     0.046033     0.046181     0.046328     0.046474   
..           ...          ...          ...          ...          ...   
196     0.047115     0.047262     0.047409     0.047555     0.047700   
197     0.045884     0.046033     0.046181     0.046328     0.046474   
198     0.044674     0.044824     0.044973     0.045121     0.045268   
199     0.043483     0.043634     0.043784     0.043933     0.044081   
200     0.042313     0.042464     0.042615     0.042765     0.042914   

     amplitude 5  amplitude 6  amplitude 7  amplitude 8  amplitude 9  ...  \
0       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
1       0.043062     0.043210     0.043357     0.043503     0.043648  ...   
2       0.044229     0.044376     0.044522     0.044667     0.044811  ...   
3       0.045415     0.045560     0.045705     0.045849     0.045993  ...   
4       0.046620     0.046764     0.046908     0.047051     0.047193  ...   
..           ...          ...          ...          ...          ...  ...   
196     0.047844     0.047987     0.048130     0.048271     0.048412  ...   
197     0.046620     0.046764     0.046908     0.047051     0.047193  ...   
198     0.045415     0.045560     0.045705     0.045849     0.045993  ...   
199     0.044229     0.044376     0.044522     0.044667     0.044811  ...   
200     0.043062     0.043210     0.043357     0.043503     0.043648  ...   

     amplitude 50  amplitude 51  amplitude 52  amplitude 53  amplitude 54  \
0        2.000000      2.000000      2.000000      2.000000      2.000000   
1        0.054570      0.054645      0.054718      0.054791      0.054864   
2        0.055566      0.055638      0.055710      0.055781      0.055852   
3        0.056570      0.056640      0.056710      0.056779      0.056847   
4        0.057581      0.057649      0.057717      0.057783      0.057850   
..            ...           ...           ...           ...           ...   
196      0.058600      0.058666      0.058731      0.058795      0.058859   
197      0.057581      0.057649      0.057717      0.057783      0.057850   
198      0.056570      0.056640      0.056710      0.056779      0.056847   
199      0.055566      0.055638      0.055710      0.055781      0.055852   
200      0.054570      0.054645      0.054718      0.054791      0.054864   

     amplitude 55  amplitude 56  amplitude 57  amplitude 58  amplitude 59  
0        2.000000      2.000000      2.000000      2.000000      2.000000  
1        0.054936      0.055007      0.055078      0.055148      0.055218  
2        0.055922      0.055991      0.056060      0.056128      0.056195  
3        0.056915      0.056982      0.057049      0.057115      0.057180  
4        0.057915      0.057980      0.058045      0.058108      0.058172  
..            ...           ...           ...           ...           ...  
196      0.058923      0.058985      0.059048      0.059109      0.059170  
197      0.057915      0.057980      0.058045      0.058108      0.058172  
198      0.056915      0.056982      0.057049      0.057115      0.057180  
199      0.055922      0.055991      0.056060      0.056128      0.056195  
200      0.054936      0.055007      0.055078      0.055148      0.055218  

[201 rows x 60 columns]

In [4]:
df_df = pd.DataFrame(np.array(df).T)
df_df.head(10)

0         1         2         3         4         5         6         7    \
0  0.0  0.042313  0.043483  0.044674  0.045884  0.047115  0.048365  0.049634   
1  0.0  0.042464  0.043634  0.044824  0.046033  0.047262  0.048511  0.049779   
2  0.0  0.042615  0.043784  0.044973  0.046181  0.047409  0.048656  0.049923   
3  0.0  0.042765  0.043933  0.045121  0.046328  0.047555  0.048801  0.050066   
4  0.0  0.042914  0.044081  0.045268  0.046474  0.047700  0.048944  0.050208   
5  0.0  0.043062  0.044229  0.045415  0.046620  0.047844  0.049087  0.050349   
6  0.0  0.043210  0.044376  0.045560  0.046764  0.047987  0.049229  0.050489   
7  0.0  0.043357  0.044522  0.045705  0.046908  0.048130  0.049370  0.050628   
8  0.0  0.043503  0.044667  0.045849  0.047051  0.048271  0.049510  0.050767   
9  0.0  0.043648  0.044811  0.045993  0.047193  0.048412  0.049649  0.050904   

        8         9    ...       191       192       193       194       195  \
0  0.050923  0.052231  ...  0.053557  0.052231  0.050923  0.049634  0.048365   
1  0.051066  0.052372  ...  0.053696  0.052372  0.051066  0.049779  0.048511   
2  0.051208  0.052512  ...  0.053835  0.052512  0.051208  0.049923  0.048656   
3  0.051349  0.052651  ...  0.053972  0.052651  0.051349  0.050066  0.048801   
4  0.051490  0.052790  ...  0.054108  0.052790  0.051490  0.050208  0.048944   
5  0.051629  0.052927  ...  0.054244  0.052927  0.051629  0.050349  0.049087   
6  0.051767  0.053064  ...  0.054378  0.053064  0.051767  0.050489  0.049229   
7  0.051905  0.053200  ...  0.054512  0.053200  0.051905  0.050628  0.049370   
8  0.052042  0.053334  ...  0.054644  0.053334  0.052042  0.050767  0.049510   
9  0.052177  0.053468  ...  0.054776  0.053468  0.052177  0.050904  0.049649   

        196       197       198       199       200  
0  0.047115  0.045884  0.044674  0.043483  0.042313  
1  0.047262  0.046033  0.044824  0.043634  0.042464  
2  0.047409  0.046181  0.044973  0.043784  0.042615  
3  0.047555  0.046328  0.045121  0.043933  0.042765  
4  0.047700  0.046474  0.045268  0.044081  0.042914  
5  0.047844  0.046620  0.045415  0.044229  0.043062  
6  0.047987  0.046764  0.045560  0.044376  0.043210  
7  0.048130  0.046908  0.045705  0.044522  0.043357  
8  0.048271  0.047051  0.045849  0.044667  0.043503  
9  0.048412  0.047193  0.045993  0.044811  0.043648  

[10 rows x 201 columns]

In [5]:
df_shuffle = df_df.sample(frac=1).reset_index(drop=True)

In [6]:
df_shuffle.head(10)

0         1         2         3         4         5         6         7    \
0  2.0  0.054112  0.055120  0.056137  0.057161  0.058194  0.059234  0.060281   
1  0.0  0.042615  0.043784  0.044973  0.046181  0.047409  0.048656  0.049923   
2  0.0  0.043936  0.045097  0.046277  0.047475  0.048691  0.049925  0.051177   
3  1.0  0.051486  0.052553  0.053630  0.054719  0.055818  0.056927  0.058046   
4  1.0  0.051964  0.053021  0.054089  0.055167  0.056255  0.057353  0.058460   
5  1.0  0.051290  0.052360  0.053442  0.054534  0.055638  0.056751  0.057875   
6  0.0  0.043062  0.044229  0.045415  0.046620  0.047844  0.049087  0.050349   
7  0.0  0.043503  0.044667  0.045849  0.047051  0.048271  0.049510  0.050767   
8  0.0  0.044504  0.045661  0.046835  0.048028  0.049238  0.050466  0.051711   
9  0.0  0.044363  0.045521  0.046697  0.047891  0.049103  0.050332  0.051579   

        8         9    ...       191       192       193       194       195  \
0  0.061335  0.062397  ...  0.063464  0.062397  0.061335  0.060281  0.059234   
1  0.051208  0.052512  ...  0.053835  0.052512  0.051208  0.049923  0.048656   
2  0.052446  0.053733  ...  0.055036  0.053733  0.052446  0.051177  0.049925   
3  0.059175  0.060313  ...  0.061461  0.060313  0.059175  0.058046  0.056927   
4  0.059577  0.060703  ...  0.061837  0.060703  0.059577  0.058460  0.057353   
5  0.059009  0.060153  ...  0.061305  0.060153  0.059009  0.057875  0.056751   
6  0.051629  0.052927  ...  0.054244  0.052927  0.051629  0.050349  0.049087   
7  0.052042  0.053334  ...  0.054644  0.053334  0.052042  0.050767  0.049510   
8  0.052973  0.054251  ...  0.055546  0.054251  0.052973  0.051711  0.050466   
9  0.052842  0.054123  ...  0.055420  0.054123  0.052842  0.051579  0.050332   

        196       197       198       199       200  
0  0.058194  0.057161  0.056137  0.055120  0.054112  
1  0.047409  0.046181  0.044973  0.043784  0.042615  
2  0.048691  0.047475  0.046277  0.045097  0.043936  
3  0.055818  0.054719  0.053630  0.052553  0.051486  
4  0.056255  0.055167  0.054089  0.053021  0.051964  
5  0.055638  0.054534  0.053442  0.052360  0.051290  
6  0.047844  0.046620  0.045415  0.044229  0.043062  
7  0.048271  0.047051  0.045849  0.044667  0.043503  
8  0.049238  0.048028  0.046835  0.045661  0.044504  
9  0.049103  0.047891  0.046697  0.045521  0.044363  

[10 rows x 201 columns]

# Shuffle Data

## Y train and Test

In [7]:
dataset = np.array(df_shuffle)
#dataset

In [8]:
Y = dataset[:,0]
Y = Y.astype(np.int64)

In [9]:
Y.size

60

In [10]:
Y

array([2, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 2, 1, 1,
       0, 0, 2, 1, 2, 2, 2, 2, 2, 1, 2, 0, 2, 2, 1, 1, 2, 2, 1, 1, 2, 1,
       0, 0, 0, 0, 2, 1, 2, 1, 2, 2, 1, 1, 0, 0, 1, 1])

### Y_train

In [11]:
Y_train = Y[0:50]
Y_train.size

50

In [12]:
Y_train

array([2, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 2, 1, 1,
       0, 0, 2, 1, 2, 2, 2, 2, 2, 1, 2, 0, 2, 2, 1, 1, 2, 2, 1, 1, 2, 1,
       0, 0, 0, 0, 2, 1])

### Y_test

In [13]:
y_test = Y[50:60]
y_test.size

10

In [14]:
y_test

array([2, 1, 2, 2, 1, 1, 0, 0, 1, 1])

## X train and test

In [15]:
X = dataset[:,1:]
X.shape

(60, 200)

### X_train

In [16]:
X_train = X[0:50,:]
X_train.shape

(50, 200)

### X_test

In [17]:
x_test = X[50:60,:]
x_test.shape

(10, 200)

#### Set: Categorical Y train and testm

In [18]:
Y_train = keras.utils.to_categorical(Y_train, num_classes=3,dtype="int32")
y_test = keras.utils.to_categorical(y_test, num_classes=3,dtype="int32")


In [19]:
Y_train

array([[0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0]], dtype=int32)

In [20]:
y_test 

array([[0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0]], dtype=int32)

In [21]:
X_train[40:41]

array([[0.05186991, 0.05292903, 0.05399875, 0.05507885, 0.05616908,
        0.05726919, 0.05837893, 0.05949803, 0.0606262 , 0.06176315,
        0.06290857, 0.06406216, 0.06522358, 0.06639251, 0.06756858,
        0.06875145, 0.06994074, 0.07113608, 0.07233708, 0.07354334,
        0.07475445, 0.07597   , 0.07718954, 0.07841265, 0.07963889,
        0.08086778, 0.08209887, 0.08333169, 0.08456576, 0.08580057,
        0.08703565, 0.08827048, 0.08950456, 0.09073736, 0.09196836,
        0.09319703, 0.09442283, 0.09564523, 0.09686367, 0.09807761,
        0.09928649, 0.10048975, 0.10168683, 0.10287716, 0.10406018,
        0.10523531, 0.10640198, 0.10755963, 0.10870768, 0.10984554,
        0.11097266, 0.11208846, 0.11319236, 0.1142838 , 0.11536221,
        0.11642702, 0.11747766, 0.11851359, 0.11953425, 0.12053908,
        0.12152755, 0.1224991 , 0.12345322, 0.12438937, 0.12530703,
        0.12620569, 0.12708484, 0.12794399, 0.12878266, 0.12960035,
        0.13039662, 0.13117099, 0.13192302, 0.13

In [22]:
Y_train[40:41]

array([[0, 1, 0]], dtype=int32)

In [23]:
#Model

In [24]:
model = Sequential()

2022-09-16 22:57:07.308941: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-09-16 22:57:07.309538: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-09-16 22:57:07.309656: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory
2022-09-16 22:57:07.309762: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory
2022-09-16 22:57:07.309884: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Co

In [25]:
model.add(Dense(64, activation='relu', input_dim=200))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(3, activation='softmax'))

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)

/home/capdoo/.local/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/gradient_descent.py:108: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(SGD, self).__init__(name, **kwargs)


In [26]:
model.compile(loss='categorical_crossentropy',optimizer=sgd,metrics=['accuracy'])

In [27]:
model.fit(X_train,Y_train,epochs=1400,batch_size=128)

Epoch 1/1400
1/1 [==============================] - 0s 428ms/step - loss: 1.1304 - accuracy: 0.2600
Epoch 2/1400
1/1 [==============================] - 0s 7ms/step - loss: 1.1124 - accuracy: 0.3800
Epoch 3/1400
1/1 [==============================] - 0s 6ms/step - loss: 1.0931 - accuracy: 0.3600
Epoch 4/1400
1/1 [==============================] - 0s 4ms/step - loss: 1.1169 - accuracy: 0.2800
Epoch 5/1400
1/1 [==============================] - 0s 6ms/step - loss: 1.1115 - accuracy: 0.3400
Epoch 6/1400
1/1 [==============================] - 0s 5ms/step - loss: 1.1324 - accuracy: 0.2600
Epoch 7/1400
1/1 [==============================] - 0s 5ms/step - loss: 1.1277 - accuracy: 0.2200
Epoch 8/1400
1/1 [==============================] - 0s 4ms/step - loss: 1.1027 - accuracy: 0.3400
Epoch 9/1400
1/1 [==============================] - 0s 4ms/step - loss: 1.1011 - accuracy: 0.3600
Epoch 10/1400
1/1 [==============================] - 0s 3ms/step - loss: 1.0943 - accuracy: 0.4600
Epoch 11/1400
1/1

In [29]:
score = model.evaluate(x_test, y_test, batch_size=128,)

1/1 [==============================] - 0s 153ms/step - loss: 0.4460 - accuracy: 0.9000


In [30]:
model.metrics_names

['loss', 'accuracy']

In [31]:
score

[0.44599756598472595, 0.8999999761581421]

In [32]:
#Test 1

In [33]:
model.predict(x_test[0:1], batch_size=None, verbose=0, steps=None)

array([[0.03661265, 0.24676661, 0.7166208 ]], dtype=float32)

In [34]:
y_test[0:1]

array([[0, 0, 1]], dtype=int32)

In [35]:
#Test 2

In [36]:
model.predict(X_train[43:44], batch_size=None, verbose=0, steps=None)

array([[0.08268157, 0.43999895, 0.47731948]], dtype=float32)

In [37]:
Y_train[43:44]

array([[0, 1, 0]], dtype=int32)