In [20]:
import keras
from keras.models import Sequential
from keras.layers import Dense,Dropout,Activation
from keras.optimizers import SGD
import numpy as np
import pandas as pd

In [21]:
def pdf(x,tar):
    mean = np.mean(x)
    std = np.std(x)+tar
    y_out = 1/(std * np.sqrt(2 * np.pi)) * np.exp( - (x - mean)**2 / (2 * std**2))
    return y_out

In [22]:
a=2
b=10

#200 x's
m2 = 0.04

x = np.arange(a, b, m2)

print("L--------")
#Low concentration
low = 0.10
inc = 0

k=0
for i in range(20):
    #print(i)
    y = pdf(x,low+inc)
    y = np.insert(y, 0, 0, axis=0)
    
    if(i==0):
        data = {"amplitude 0":y}
        df = pd.DataFrame(data)
    else:    
        name = "amplitude "+str(k)
        df[name] = y
    
    
    inc = inc+0.005
    k+=1
    
print("M--------")
#Medium concentration
medium = 0.40
inc = 0
for i in range(20):
    #print(medium+inc)
    y = pdf(x,medium+inc)
    y = np.insert(y, 0, 1, axis=0)
    
    name = "amplitude "+str(k)
    df[name] = y
    
    inc = inc+0.005
    

    k+=1
    
    
print("H--------")
#High concentration
high = 0.60
inc = 0.0 
for i in range(20):
    #print(high+inc)
    y = pdf(x, high+inc)
    y = np.insert(y, 0, 2, axis=0)
    
    name = "amplitude "+str(k)
    df[name] = y
    
    inc = inc+0.005
    k+=1
    
#print(y)
df 

L--------
M--------
H--------


amplitude 0  amplitude 1  amplitude 2  amplitude 3  amplitude 4  \
0       0.000000     0.000000     0.000000     0.000000     0.000000   
1       0.042313     0.042464     0.042615     0.042765     0.042914   
2       0.043483     0.043634     0.043784     0.043933     0.044081   
3       0.044674     0.044824     0.044973     0.045121     0.045268   
4       0.045884     0.046033     0.046181     0.046328     0.046474   
..           ...          ...          ...          ...          ...   
196     0.047115     0.047262     0.047409     0.047555     0.047700   
197     0.045884     0.046033     0.046181     0.046328     0.046474   
198     0.044674     0.044824     0.044973     0.045121     0.045268   
199     0.043483     0.043634     0.043784     0.043933     0.044081   
200     0.042313     0.042464     0.042615     0.042765     0.042914   

     amplitude 5  amplitude 6  amplitude 7  amplitude 8  amplitude 9  ...  \
0       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
1       0.043062     0.043210     0.043357     0.043503     0.043648  ...   
2       0.044229     0.044376     0.044522     0.044667     0.044811  ...   
3       0.045415     0.045560     0.045705     0.045849     0.045993  ...   
4       0.046620     0.046764     0.046908     0.047051     0.047193  ...   
..           ...          ...          ...          ...          ...  ...   
196     0.047844     0.047987     0.048130     0.048271     0.048412  ...   
197     0.046620     0.046764     0.046908     0.047051     0.047193  ...   
198     0.045415     0.045560     0.045705     0.045849     0.045993  ...   
199     0.044229     0.044376     0.044522     0.044667     0.044811  ...   
200     0.043062     0.043210     0.043357     0.043503     0.043648  ...   

     amplitude 50  amplitude 51  amplitude 52  amplitude 53  amplitude 54  \
0        2.000000      2.000000      2.000000      2.000000      2.000000   
1        0.054570      0.054645      0.054718      0.054791      0.054864   
2        0.055566      0.055638      0.055710      0.055781      0.055852   
3        0.056570      0.056640      0.056710      0.056779      0.056847   
4        0.057581      0.057649      0.057717      0.057783      0.057850   
..            ...           ...           ...           ...           ...   
196      0.058600      0.058666      0.058731      0.058795      0.058859   
197      0.057581      0.057649      0.057717      0.057783      0.057850   
198      0.056570      0.056640      0.056710      0.056779      0.056847   
199      0.055566      0.055638      0.055710      0.055781      0.055852   
200      0.054570      0.054645      0.054718      0.054791      0.054864   

     amplitude 55  amplitude 56  amplitude 57  amplitude 58  amplitude 59  
0        2.000000      2.000000      2.000000      2.000000      2.000000  
1        0.054936      0.055007      0.055078      0.055148      0.055218  
2        0.055922      0.055991      0.056060      0.056128      0.056195  
3        0.056915      0.056982      0.057049      0.057115      0.057180  
4        0.057915      0.057980      0.058045      0.058108      0.058172  
..            ...           ...           ...           ...           ...  
196      0.058923      0.058985      0.059048      0.059109      0.059170  
197      0.057915      0.057980      0.058045      0.058108      0.058172  
198      0.056915      0.056982      0.057049      0.057115      0.057180  
199      0.055922      0.055991      0.056060      0.056128      0.056195  
200      0.054936      0.055007      0.055078      0.055148      0.055218  

[201 rows x 60 columns]

In [23]:
df_df = pd.DataFrame(np.array(df).T)
df_df.head(10)

0         1         2         3         4         5         6         7    \
0  0.0  0.042313  0.043483  0.044674  0.045884  0.047115  0.048365  0.049634   
1  0.0  0.042464  0.043634  0.044824  0.046033  0.047262  0.048511  0.049779   
2  0.0  0.042615  0.043784  0.044973  0.046181  0.047409  0.048656  0.049923   
3  0.0  0.042765  0.043933  0.045121  0.046328  0.047555  0.048801  0.050066   
4  0.0  0.042914  0.044081  0.045268  0.046474  0.047700  0.048944  0.050208   
5  0.0  0.043062  0.044229  0.045415  0.046620  0.047844  0.049087  0.050349   
6  0.0  0.043210  0.044376  0.045560  0.046764  0.047987  0.049229  0.050489   
7  0.0  0.043357  0.044522  0.045705  0.046908  0.048130  0.049370  0.050628   
8  0.0  0.043503  0.044667  0.045849  0.047051  0.048271  0.049510  0.050767   
9  0.0  0.043648  0.044811  0.045993  0.047193  0.048412  0.049649  0.050904   

        8         9    ...       191       192       193       194       195  \
0  0.050923  0.052231  ...  0.053557  0.052231  0.050923  0.049634  0.048365   
1  0.051066  0.052372  ...  0.053696  0.052372  0.051066  0.049779  0.048511   
2  0.051208  0.052512  ...  0.053835  0.052512  0.051208  0.049923  0.048656   
3  0.051349  0.052651  ...  0.053972  0.052651  0.051349  0.050066  0.048801   
4  0.051490  0.052790  ...  0.054108  0.052790  0.051490  0.050208  0.048944   
5  0.051629  0.052927  ...  0.054244  0.052927  0.051629  0.050349  0.049087   
6  0.051767  0.053064  ...  0.054378  0.053064  0.051767  0.050489  0.049229   
7  0.051905  0.053200  ...  0.054512  0.053200  0.051905  0.050628  0.049370   
8  0.052042  0.053334  ...  0.054644  0.053334  0.052042  0.050767  0.049510   
9  0.052177  0.053468  ...  0.054776  0.053468  0.052177  0.050904  0.049649   

        196       197       198       199       200  
0  0.047115  0.045884  0.044674  0.043483  0.042313  
1  0.047262  0.046033  0.044824  0.043634  0.042464  
2  0.047409  0.046181  0.044973  0.043784  0.042615  
3  0.047555  0.046328  0.045121  0.043933  0.042765  
4  0.047700  0.046474  0.045268  0.044081  0.042914  
5  0.047844  0.046620  0.045415  0.044229  0.043062  
6  0.047987  0.046764  0.045560  0.044376  0.043210  
7  0.048130  0.046908  0.045705  0.044522  0.043357  
8  0.048271  0.047051  0.045849  0.044667  0.043503  
9  0.048412  0.047193  0.045993  0.044811  0.043648  

[10 rows x 201 columns]

In [24]:
df_shuffle = df_df.sample(frac=1).reset_index(drop=True)

In [25]:
df_shuffle.head(10)

0         1         2         3         4         5         6         7    \
0  2.0  0.055078  0.056060  0.057049  0.058045  0.059048  0.060057  0.061073   
1  2.0  0.055218  0.056195  0.057180  0.058172  0.059170  0.060175  0.061186   
2  0.0  0.044363  0.045521  0.046697  0.047891  0.049103  0.050332  0.051579   
3  0.0  0.044783  0.045937  0.047110  0.048300  0.049507  0.050731  0.051973   
4  2.0  0.054344  0.055346  0.056356  0.057374  0.058400  0.059433  0.060473   
5  2.0  0.054645  0.055638  0.056640  0.057649  0.058666  0.059689  0.060720   
6  2.0  0.054420  0.055420  0.056428  0.057444  0.058467  0.059498  0.060535   
7  2.0  0.055007  0.055991  0.056982  0.057980  0.058985  0.059997  0.061016   
8  1.0  0.051486  0.052553  0.053630  0.054719  0.055818  0.056927  0.058046   
9  1.0  0.050269  0.051358  0.052458  0.053571  0.054695  0.055831  0.056978   

        8         9    ...       191       192       193       194       195  \
0  0.062095  0.063123  ...  0.064156  0.063123  0.062095  0.061073  0.060057   
1  0.062203  0.063226  ...  0.064254  0.063226  0.062203  0.061186  0.060175   
2  0.052842  0.054123  ...  0.055420  0.054123  0.052842  0.051579  0.050332   
3  0.053231  0.054505  ...  0.055795  0.054505  0.053231  0.051973  0.050731   
4  0.061520  0.062573  ...  0.063633  0.062573  0.061520  0.060473  0.059433   
5  0.061757  0.062800  ...  0.063849  0.062800  0.061757  0.060720  0.059689   
6  0.061580  0.062631  ...  0.063688  0.062631  0.061580  0.060535  0.059498   
7  0.062040  0.063070  ...  0.064106  0.063070  0.062040  0.061016  0.059997   
8  0.059175  0.060313  ...  0.061461  0.060313  0.059175  0.058046  0.056927   
9  0.058136  0.059305  ...  0.060484  0.059305  0.058136  0.056978  0.055831   

        196       197       198       199       200  
0  0.059048  0.058045  0.057049  0.056060  0.055078  
1  0.059170  0.058172  0.057180  0.056195  0.055218  
2  0.049103  0.047891  0.046697  0.045521  0.044363  
3  0.049507  0.048300  0.047110  0.045937  0.044783  
4  0.058400  0.057374  0.056356  0.055346  0.054344  
5  0.058666  0.057649  0.056640  0.055638  0.054645  
6  0.058467  0.057444  0.056428  0.055420  0.054420  
7  0.058985  0.057980  0.056982  0.055991  0.055007  
8  0.055818  0.054719  0.053630  0.052553  0.051486  
9  0.054695  0.053571  0.052458  0.051358  0.050269  

[10 rows x 201 columns]

# Shuffle Data

## Y train and Test

In [26]:
dataset = np.array(df_shuffle)
#dataset

In [27]:
Y = dataset[:,0]
Y = Y.astype(np.int64)

In [28]:
Y.size

60

In [29]:
Y

array([2, 2, 0, 0, 2, 2, 2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 0, 0, 1, 2, 1, 0,
       0, 1, 0, 0, 1, 2, 2, 2, 1, 0, 1, 0, 0, 1, 2, 1, 1, 0, 2, 0, 0, 1,
       2, 1, 2, 0, 1, 1, 1, 1, 2, 0, 0, 0, 0, 2, 0, 1])

### Y_train

In [30]:
Y_train = Y[0:50]
Y_train.size

50

In [31]:
Y_train

array([2, 2, 0, 0, 2, 2, 2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 0, 0, 1, 2, 1, 0,
       0, 1, 0, 0, 1, 2, 2, 2, 1, 0, 1, 0, 0, 1, 2, 1, 1, 0, 2, 0, 0, 1,
       2, 1, 2, 0, 1, 1])

### Y_test

In [32]:
y_test = Y[50:60]
y_test.size

10

In [33]:
y_test

array([1, 1, 2, 0, 0, 0, 0, 2, 0, 1])

## X train and test

In [34]:
X = dataset[:,1:]
X.shape

(60, 200)

### X_train

In [35]:
X_train = X[0:50,:]
X_train.shape

(50, 200)

### X_test

In [36]:
x_test = X[50:60,:]
x_test.shape

(10, 200)

#### Set: Categorical Y train and testm

In [37]:
Y_train = keras.utils.to_categorical(Y_train, num_classes=3,dtype="int32")
y_test = keras.utils.to_categorical(y_test, num_classes=3,dtype="int32")


In [38]:
Y_train

array([[0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0]], dtype=int32)

In [39]:
y_test 

array([[0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0]], dtype=int32)

In [41]:
X_train[40:41]

array([[0.05411221, 0.05512033, 0.05613678, 0.0571613 , 0.05819368,
        0.05923365, 0.06028097, 0.06133537, 0.06239657, 0.06346431,
        0.06453828, 0.06561818, 0.06670372, 0.06779458, 0.06889043,
        0.06999094, 0.07109577, 0.07220459, 0.07331702, 0.07443271,
        0.07555129, 0.07667239, 0.07779561, 0.07892057, 0.08004688,
        0.08117412, 0.08230189, 0.08342976, 0.08455733, 0.08568416,
        0.08680982, 0.08793387, 0.08905587, 0.09017537, 0.09129192,
        0.09240506, 0.09351434, 0.09461929, 0.09571945, 0.09681434,
        0.09790351, 0.09898646, 0.10006274, 0.10113187, 0.10219336,
        0.10324674, 0.10429153, 0.10532725, 0.10635343, 0.10736958,
        0.10837523, 0.10936991, 0.11035314, 0.11132445, 0.11228337,
        0.11322944, 0.11416219, 0.11508117, 0.11598591, 0.11687597,
        0.11775091, 0.11861028, 0.11945365, 0.12028058, 0.12109066,
        0.12188347, 0.12265859, 0.12341563, 0.12415419, 0.12487389,
        0.12557434, 0.12625518, 0.12691605, 0.12

In [43]:
Y_train[40:41]

array([[0, 0, 1]], dtype=int32)

In [ ]:
#Model

In [59]:
model = Sequential()

In [60]:
model.add(Dense(64, activation='relu', input_dim=200))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(3, activation='softmax'))

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)

In [61]:
model.compile(loss='categorical_crossentropy',optimizer=sgd,metrics=['accuracy'])

In [ ]:
model.fit(X_train,Y_train,epochs=2000,batch_size=128)

Epoch 1/2000
1/1 [==============================] - 0s 433ms/step - loss: 1.0995 - accuracy: 0.2600
Epoch 2/2000
1/1 [==============================] - 0s 3ms/step - loss: 1.1307 - accuracy: 0.3000
Epoch 3/2000
1/1 [==============================] - 0s 4ms/step - loss: 1.0902 - accuracy: 0.3800
Epoch 4/2000
1/1 [==============================] - 0s 4ms/step - loss: 1.1362 - accuracy: 0.3000
Epoch 5/2000
1/1 [==============================] - 0s 3ms/step - loss: 1.1367 - accuracy: 0.3200
Epoch 6/2000
1/1 [==============================] - 0s 9ms/step - loss: 1.0937 - accuracy: 0.3800
Epoch 7/2000
1/1 [==============================] - 0s 4ms/step - loss: 1.1279 - accuracy: 0.2800
Epoch 8/2000
1/1 [==============================] - 0s 4ms/step - loss: 1.0934 - accuracy: 0.3600
Epoch 9/2000
1/1 [==============================] - 0s 4ms/step - loss: 1.1217 - accuracy: 0.3400
Epoch 10/2000
1/1 [==============================] - 0s 5ms/step - loss: 1.0771 - accuracy: 0.4400
Epoch 11/2000
1/1

In [ ]:
#x_test = x_train[55:60]
#y_test = y_train[55:60]

In [50]:
score = model.evaluate(x_test, y_test, batch_size=128,)

1/1 [==============================] - 0s 165ms/step - loss: 1.1307 - accuracy: 0.2000


In [51]:
model.metrics_names

['loss', 'accuracy']

In [52]:
score

[1.130658507347107, 0.20000000298023224]

In [ ]:
#Test 1

In [53]:
model.predict(x_test[0:1], batch_size=None, verbose=0, steps=None)

array([[0.29985535, 0.33829492, 0.3618497 ]], dtype=float32)

In [54]:
y_test[0:1]

array([[0, 1, 0]], dtype=int32)

In [ ]:
#Test 2

In [56]:
model.predict(X_train[43:44], batch_size=None, verbose=0, steps=None)

array([[0.29985255, 0.3382954 , 0.36185202]], dtype=float32)

In [58]:
Y_train[43:44]

array([[0, 1, 0]], dtype=int32)