In [46]:
import keras
from keras.models import Sequential
from keras.layers import Dense,Dropout,Activation
from keras.optimizers import SGD
import numpy as np
import pandas as pd

In [47]:

#Generate dummy data
x_train = np.random.random((1000,20))
y_train = keras.utils.to_categorical(np.random.randint(10, size=(1000,1)), num_classes=10)

x_test = np.random.random((100,20))
y_test = keras.utils.to_categorical(np.random.randint(10, size=(100,1)), num_classes=10)


In [48]:
x_train
x_train_df = pd.DataFrame(x_train)

In [49]:
x_train_df

0         1         2         3         4         5         6   \
0    0.830461  0.252101  0.916772  0.585834  0.513784  0.746967  0.992163   
1    0.369492  0.473598  0.238138  0.446601  0.465056  0.250152  0.931949   
2    0.402855  0.985386  0.803987  0.004672  0.517102  0.804108  0.532742   
3    0.920168  0.210759  0.931599  0.188317  0.675852  0.764837  0.926446   
4    0.698040  0.465917  0.973971  0.768795  0.352221  0.625919  0.041461   
..        ...       ...       ...       ...       ...       ...       ...   
995  0.993972  0.803178  0.478022  0.492548  0.151637  0.564705  0.178478   
996  0.871251  0.917453  0.061446  0.149964  0.582711  0.387395  0.634925   
997  0.156164  0.929260  0.048814  0.184709  0.840406  0.104146  0.322590   
998  0.978287  0.887633  0.202345  0.914080  0.343484  0.253952  0.299353   
999  0.131988  0.986468  0.478914  0.527362  0.849356  0.121389  0.233197   

           7         8         9         10        11        12        13  \
0    0.399048  0.936291  0.363631  0.259240  0.975595  0.171035  0.542400   
1    0.120964  0.185184  0.521602  0.540880  0.540383  0.600358  0.310699   
2    0.940809  0.450641  0.580845  0.711378  0.649677  0.244035  0.034160   
3    0.808682  0.677077  0.742275  0.187825  0.520216  0.242144  0.209366   
4    0.286514  0.635795  0.975377  0.098126  0.555731  0.019931  0.127158   
..        ...       ...       ...       ...       ...       ...       ...   
995  0.365742  0.542544  0.751643  0.912775  0.028364  0.013117  0.107910   
996  0.719533  0.374738  0.137669  0.599401  0.740694  0.515932  0.907186   
997  0.262008  0.283898  0.070377  0.604333  0.908230  0.268022  0.881346   
998  0.945828  0.904729  0.456132  0.132801  0.245010  0.787572  0.861874   
999  0.600287  0.406409  0.998428  0.911999  0.933101  0.359365  0.478814   

           14        15        16        17        18        19  
0    0.623324  0.469361  0.878946  0.238861  0.225269  0.939979  
1    0.716812  0.062166  0.440008  0.017771  0.233747  0.603559  
2    0.735298  0.976640  0.115616  0.051914  0.042054  0.798105  
3    0.769652  0.899913  0.136030  0.853805  0.062445  0.436695  
4    0.725738  0.065074  0.367792  0.530409  0.592315  0.100458  
..        ...       ...       ...       ...       ...       ...  
995  0.370592  0.278609  0.858705  0.061313  0.018281  0.614641  
996  0.809868  0.300478  0.075010  0.289066  0.246021  0.158354  
997  0.534712  0.511542  0.378252  0.629865  0.202039  0.980268  
998  0.396034  0.602603  0.579746  0.976257  0.139080  0.470942  
999  0.511463  0.940472  0.194163  0.829124  0.021783  0.544345  

[1000 rows x 20 columns]

In [50]:
y_train_df = pd.DataFrame(y_train)
y_train_df

0    1    2    3    4    5    6    7    8    9
0    1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1    0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
2    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
3    0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
4    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
995  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
996  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
997  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
998  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
999  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0

[1000 rows x 10 columns]

In [28]:
#Understanding

In [29]:
x_train[50:51]

array([[0.4369293 , 0.3550653 , 0.94474398, 0.81024662, 0.90458484,
        0.65962187, 0.27564496, 0.61808446, 0.75936779, 0.34057308,
        0.97352488, 0.95875978, 0.00174666, 0.50299475, 0.26238944,
        0.58154637, 0.05656692, 0.80897983, 0.03261332, 0.4376227 ]])

In [30]:
y_train[50:51]

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [31]:
x_test[0]

array([0.01365377, 0.11904494, 0.27835105, 0.51765336, 0.85508079,
       0.18360009, 0.88577028, 0.49431654, 0.56715955, 0.66634855,
       0.77330939, 0.83778733, 0.2933796 , 0.9798574 , 0.3253454 ,
       0.81133531, 0.18199663, 0.79870527, 0.04137132, 0.51033763])

In [32]:
y_test[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32)

In [33]:
##Create the model

In [35]:
model = Sequential()

In [36]:
model.add(Dense(64, activation='relu', input_dim=20))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)

/home/capdoo/.local/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/gradient_descent.py:108: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(SGD, self).__init__(name, **kwargs)


In [37]:
model.compile(loss='categorical_crossentropy',optimizer=sgd,metrics=['accuracy'])

In [38]:
model.fit(x_train,y_train,epochs=1000,batch_size=128)

Epoch 1/1000
8/8 [==============================] - 1s 2ms/step - loss: 2.3682 - accuracy: 0.1160
Epoch 2/1000
8/8 [==============================] - 0s 2ms/step - loss: 2.3314 - accuracy: 0.1010
Epoch 3/1000
8/8 [==============================] - 0s 2ms/step - loss: 2.3276 - accuracy: 0.1120
Epoch 4/1000
8/8 [==============================] - 0s 2ms/step - loss: 2.3179 - accuracy: 0.0950
Epoch 5/1000
8/8 [==============================] - 0s 3ms/step - loss: 2.3136 - accuracy: 0.1100
Epoch 6/1000
8/8 [==============================] - 0s 3ms/step - loss: 2.3107 - accuracy: 0.1140
Epoch 7/1000
8/8 [==============================] - 0s 2ms/step - loss: 2.3099 - accuracy: 0.1060
Epoch 8/1000
8/8 [==============================] - 0s 2ms/step - loss: 2.3130 - accuracy: 0.0910
Epoch 9/1000
8/8 [==============================] - 0s 1ms/step - loss: 2.2993 - accuracy: 0.1150
Epoch 10/1000
8/8 [==============================] - 0s 3ms/step - loss: 2.2994 - accuracy: 0.1160
Epoch 11/1000
8/8 [

In [39]:
score = model.evaluate(x_test, y_test, batch_size=128,)

1/1 [==============================] - 0s 153ms/step - loss: 2.4767 - accuracy: 0.1300


In [40]:
model.metrics_names

['loss', 'accuracy']

In [44]:
score

[2.476651668548584, 0.12999999523162842]

In [45]:
#Prediction

In [42]:
model.predict(x_train[0:1], batch_size=None, verbose=0, steps=None)

array([[0.03122527, 0.16421205, 0.035437  , 0.05151023, 0.04296144,
        0.23129773, 0.0893388 , 0.06178515, 0.16871507, 0.1235173 ]],
      dtype=float32)

In [43]:
y_train[0:1]

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)